<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Comments\Commands\" />
    <Folder Include="Features\Comments\DTOs\" />
    <Folder Include="Features\Comments\Queries\" />
    <Folder Include="Features\Projects\Commands\" />
    <Folder Include="Features\Projects\DTOs\" />
    <Folder Include="Features\Projects\Queries\" />
    <Folder Include="Features\Task\Commands\" />
    <Folder Include="Features\Task\DTOs\" />
    <Folder Include="Features\Task\Queries\" />
  </ItemGroup>

</Project>
